---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: "{% if api_key != \"\" %}https://retroachievements.org/API/API_GetUserSummary.php?y={{ api_key }}&g=5&a=20&u={{username}}\r\n\r\nhttps://retroachievements.org/API/API_GetUserRecentlyPlayedGames.php?y={{ api_key }}&u={{username}}\r\n{% else %}\r\nhttps://raw.githubusercontent.com/ExcuseMi/trmnl-retroachievements-plugins/refs/heads/main/stub_data/IDX_0.json\r\n\r\nhttps://raw.githubusercontent.com/ExcuseMi/trmnl-retroachievements-plugins/refs/heads/main/stub_data/IDX_1.json\r\n{% endif %}"
polling_headers: ''
polling_body: ''
id: 176378
custom_fields:
- keyname: about
  name: About This Plugin
  field_type: author_bio
  description: Unofficial <b>RetroAchievements</b> plugin displaying a users <b>recent games</b>.
  github_url: https://github.com/ExcuseMi/trmnl-retroachievements-plugins
  learn_more_url: https://retroachievements.org/
- keyname: api_key
  field_type: string
  name: Retro Achievements Web API Key
  optional: true
  description: You can find your <b>Web API Key</b> under <b>Authentication</b> in your <b><a href="https://retroachievements.org/RetroAchievement settings">RetroAchievement settings</a></b>
  placeholder: RetroAchievements API Key
- keyname: username
  field_type: string
  name: Target username or ULID
  description: Target username or ULID
  placeholder: username or ULID
- keyname: artstyle
  field_type: select
  options:
  - Icon
  - Title
  - Ingame
  - BoxArt
  default: icon
  name: Artstyle
  description: Select the artstyle
- keyname: hardcore_only
  field_type: select
  options:
  - 'No'
  - 'Yes'
  default: 'No'
  name: Hardcore only
  description: Only show achievements and points achieved without additional emulator features.
- keyname: include_points
  field_type: select
  options:
  - 'Yes'
  - 'No'
  default: 'Yes'
  name: Include points
  description: Include the points progress bar
name: 'RetroAchievements: Recent Games'
refresh_interval: 15
